uploads = []
generated = []

[[outputs]]
id = "eLb-3JXx3raQIsEzh0Loj"
uri = "file://gachapull_project.tar.gz"
type = "unspecified"
title = "GachaPull - Complete Project (Code + Database + Docs)"

[[outputs]]
id = "EXV10cqmlpyMFNNZ8_ekw"
uri = "file://gachapull_source.zip"
type = "unspecified"
title = "GachaPull - Source Code + Database + Dokumentasi (0.4 MB)"

[[outputs]]
id = "kbSCNf2KZPvbm8nFgQ_gb"
uri = "file://gachapull-latest.zip"
type = "unspecified"
title = "GachaPull — Source Code Terbaru"

[[outputs]]
id = "ZSGqj7NOlx-PHbgNe2C6j"
uri = "file://gachapull-src.zip"
type = "unspecified"
title = "GachaPull — Source Code"

[[outputs]]
id = "rxuq0YZL0KcGBsxuwPDDz"
uri = "file://gachapull_export.tar.gz"
type = "unspecified"
title = "GachaPull — Source Code + Database (tar.gz)"

[[outputs]]
id = "uW_7jEya6ZQ6_d_ciT0Jt"
uri = "file://INSTALLATION.md"
type = "text"
title = "Panduan Instalasi & Deployment"

[[outputs]]
id = "EtyAq2C6O6VzfLafYgJUQ"
uri = "file://gachapull.zip"
type = "unspecified"
title = "GachaPull — Source Code + Database (ZIP, 190KB)"
